name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 168.181.185.182
          username: fran
          key: ${{ secrets.VPS_KEY }}
          port: 5973
          script: |
            cd /var/www/html/resde
            git fetch origin
            git reset --hard origin/master
